### PR TITLE
Updated Sources-API to OpenAPI 3.0.0

### PR DESCRIPTION
**Pull request by abellotti**
Updated Sources-API to OpenAPI 3.0.0 specification
- public/doc/openapi-3-v0.1.0.json
- bundle exec rake openapi:generate

Now Leveraging OpenAPI library from manageiq-api-common

This is a prerequisite to enabling filtering with the sources api.

### CODE REVIEW

**Comment by agrare** [comment]
Hey @abellotti testing this and want to make sure I've got it right:

```
curl -H "x-rh-identity: \"eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEyMzQifX0=\n\"" http://localhost:3000/api/v0.1/sources/1 2>/dev/null | python -m json.tool
{
    "created_at": "2019-04-11T17:27:23Z",
    "id": "1",
    "name": "OCP",
    "source_type_id": "1",
    "tenant": "1234",
    "uid": "19bbe990-bfa0-4ad0-a52f-4b25ddeada80",
    "updated_at": "2019-04-11T17:27:23Z"
}
```

```
curl -H "x-rh-identity: \"eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEyMzQifX0=\n\"" http://localhost:3000/api/v0.1/sources?filter[name]=OCP 2>/dev/null | python -m json.tool
{
    "errors": [
        {
            "detail": "found unpermitted parameter: :filter",
            "status": 400
        }
    ]
}
```

```
curl -H "x-rh-identity: \"eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEyMzQifX0=\n\"" http://localhost:3000/api/v0.1/sources?filter[id]=1 2>/dev/null | python -m json.tool
{
    "errors": [
        {
            "detail": "found unpermitted parameter: :filter",
            "status": 400
        }
    ]
}
```

**Comment by agrare** [comment]
:man_facepalming: nevermind I see this is just moving to openapi 3.0

**Comment by abellotti** [comment]
Thanks for merging 🙇 yes, I'll add filtering in the followup PR.

**Pull request merged**
