### PR TITLE
Add URL validator to DDF schemas

### PR DESCRIPTION
**Pull request by rvsia**
**Description**

- Adds an URL validator for URL fields

Accepts all kinds of address (ipv4, ipv6, with/out port, etc.), the only part which is required is protocol identifier. 

@gtanzillo Which protocols are we going to support? Right now, it is set to accept only `http`,`https`, but anything else could be added. Or we could make the protocol optional too.

### CODE REVIEW

**Comment by gtanzillo** [comment]
@rvsia 
>@gtanzillo Which protocols are we going to support? Right now, it is set to accept only http,https, but anything else could be added. Or we could make the protocol optional too.

I think that's all we need to support @agrare?

**Comment by agrare** [comment]
I'm not sure what protocol we'd need for receptor-over-http but I don't think the receptor team knows either so we can cross that bridge when we get there.  http+https is good for now

**Comment by rvsia** [comment]
Good to hear it, so this PR should be fine then.

**Comment by rvsia** [comment]
Closes TPINVTRY-351

**Pull request merged**
