### PR TITLE
Add imported column to sources table

### PR DESCRIPTION
**Pull request by lpichler**
TPINVTRY-632
after UX discussion  we decided to have read-only column here, see comments and mockup in the ticket.

source api client https://github.com/ManageIQ/sources-api-client-ruby/pull/12

@miq-bot assign @agrare

### CODE REVIEW

**Comment by agrare** [comment]
Hm I'm not sure that "read-only" is what I'd call this.  You might still want to set different applications to make use of the CFME data which I wouldn't expect to do for a "read-only" source.

**Comment by slemrmartin** [comment]
Also it should be possible to delete from UI (when customer wants to stop sync from CF), so I'm not sure about "read-only" flag in both db and UI too.   
And import through sync-processor should not only check existence, but it should update name if changed in CF, so from API's point of view, it's editable so db can use "imported" flag regardless how it is called in UI

**Comment by lpichler** [comment]
@agrare, as @slemrmartin said, are you ok with `imported` ? If so I will change related PRs

thanks!

**Comment by agrare** [comment]
If we just want to show that a source was imported then I'm good with that.

If we care about what it was imported from then I think a label would be better, e.g. we could have a source imported from CFME, from Ansible Analytics, or from Openshift Online.

**Comment by terezanovotna** [comment]
This clarifies the use case. We definitely want to tell the user that this source is somehow different than other sources as it really cannot be edited. 

I suggest using "imported" label - sounds like a good wording? and then on a pop up give more detail where this comes from - CFME, Ansible Analytics etc.

**Comment by slemrmartin** [comment]
then label can be "imported": string. When blank, then it's editable in UI, when non-blank then what @terezanovotna wrote

**Comment by agrare** [comment]
Yup, and the label val could be what it is imported from

**Comment by slemrmartin** [comment]
cc @rvsia

**Comment by lpichler** [comment]
done 👍  (also related PRs are updated )

**Comment by agrare** [comment]
I was picturing an actual tag but this works too, side note we don't actually have tags/taggings on sources at all (?!) We should get on that

**Pull request merged**
